version: '2'
services:
  db:
    image: postgres
  wakuwaku5_rails_web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/wakuwaku5_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
